### ISSUE TITLE
Officially supported buildpack?

### ISSUE THREAD

**Issue by vitalbone** [heroku/heroku-buildpack-jvm-common#100]
Is this buildpack part of the officially supported buildpacks mentioned in https://devcenter.heroku.com/articles/buildpacks#officially-supported-buildpacks ?

I ask because I was wondering if I can add:
```json
"buildpacks": [{ "url": "heroku/jvm" }]
```

instead of:

```json
"buildpacks": [{ "url": "https://github.com/heroku/heroku-buildpack-jvm-common" }]
```

in my `app.json` ?

If so, could you please update the docs mentioned above.

Thanks

**Comment by jkutner** [comment]
Yes, it is officially supported. I've updated that doc (thanks for the heads up)
