### ISSUE TITLE
Copy from REDIS_URL to SPRING_REDIS_URL

### ISSUE THREAD

**Issue by seijikohara** [heroku/heroku-buildpack-jvm-common#111]
Please provide `SPRING_REDIS_URL` like `SPRING_DATASOURCE_URL`.

**Comment by jkutner** [comment]
@seijikohara is `SPRING_REDIS_URL` honored "automatically by Spring in the same way as `SPRING_DATASOURCE_URL`? 

Are there any special formatting requirements beyond a normal `redis://` URL?

It seems a little different in that is a vendor specific URL, but in general I think this is a good improvement to add.

**Comment by seijikohara** [comment]
@jkutner 
I want `SPRING_REDIS_URL` to be generated from `REDIS_URL` just like `SPRING_DATASOURCE_URL` is generated from `DATABASE_URL`.
I think `SPRING_REDIS_URL` is exactly the same as `REDIS_URL`.
Actually, I manually set `SPRING_REDIS_URL`, which is a copy of `REDIS_URL`, to run Spring application.
I have never used anything other than Heroku Redis, so I don't know the difference between vendors.

**Comment by jkutner** [comment]
@seijikohara does Spring automatically use `SPRING_REDIS_URL`?

Until this is implemented, you can dynamically set this env var in your app by creating a `.profile` with the following contents:

```
export SPRING_REDIS_URL="${REDIS_URL:-}"
```

Then add the `.profile` to Git. This will prevent the need for setting the var with `heroku config:set`

**Comment by seijikohara** [comment]
@jkutner 
> @seijikohara does Spring automatically use `SPRING_REDIS_URL`?

Yes, Spring Boot Application will automatically reference `SPRING_REDIS_URL`.

> Until this is implemented, you can dynamically set this env var in your app by creating a `.profile` with the following contents:
> 
> ```
> export SPRING_REDIS_URL="${REDIS_URL:-}"
> ```
> 
> Then add the `.profile` to Git. This will prevent the need for setting the var with `heroku config:set`

Okay, try using `.profile`. Thank you!

**Comment by jkutner** [comment]
Ok, that makes sense. We'll prioritize the work, and update this issue as we work on it.
