### ISSUE TITLE
Cache doesn't bust on system.properties

### ISSUE THREAD

**Issue by jabrown85** [heroku/heroku-buildpack-jvm-common#125]
The cache is not being properly invalidated if a `system.properties` is introduced which changes the version of `java` to be installed. 

First build with no `system.properties`
```
$ pack build javatest --builder heroku/functions-buildpacks -v --clear-cache 
... snip ...
[builder]
[builder] [Installing Java]
[builder] JDK 1.8 installed
[builder] JRE 1.8 installed
[builder]
[builder] [Installing Maven 3.6.2]
[builder]
$ docker run javatest -- java -version
openjdk version "1.8.0_232-heroku"
OpenJDK Runtime Environment (build 1.8.0_232-heroku-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)
```
Then add a `system.properties` with `java.runtime.version=11` as the contents and run again without clearing cache.

```
$ pack build javatest --builder heroku/functions-buildpacks -v
... snip ...
[builder] [Installing Java]
[builder] JDK 11 installed
[builder] JRE 11 installed
[builder]
[builder] [Installing Maven 3.6.2]
$ docker run javatest -- java -version
openjdk version "1.8.0_232-heroku"
OpenJDK Runtime Environment (build 1.8.0_232-heroku-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)
```

Expected version `11` to be installed, but `1.8` remained. The output of the buildpack seems like it indicates it shouldn't be using the cache, but it ends up using the cache anyway instead of installing fresh. `--clear-cache` works around the problem for now.

**Comment by Malax** [comment]
Fix released in v95 and added to `pack-images` here: https://github.com/heroku/pack-images/pull/58
