### ISSUE TITLE
cannot stat ‘//opt/with_jmap’: No such file or directory

### ISSUE THREAD

**Issue by benzen** [heroku/heroku-buildpack-jvm-common#19]
The boot buildpack also use this, but it seams that there is an issue when installing the jdk
https://github.com/pandeiro/heroku-buildpack-boot/blob/master/bin/compile#L39-l43

**Comment by jkutner** [comment]
Was this resolved? Sorry for losing track of the issue.

**Comment by benzen** [comment]
I thune i had to recreate my app

Benjamin Dreux
