### ISSUE TITLE
Unsupported Java version: 1.8

### ISSUE THREAD

**Issue by ejust** [heroku/heroku-buildpack-jvm-common#24]
Its seems this modification: https://github.com/heroku/heroku-buildpack-jvm-common/commit/b206f9ab0a06d3e4e5db6393632421125677b574
It introduces an regression on the heroku-buildpack-java buildpack concerning the Java version detection.

We use Java 1.8 and we don't provide system.properties file to use default version.
We have also try to put an system.properties with: java.runtime.version=1.8.0_102 without success.

The java version is not discovered properly during the build:

> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-java.git
> Detected Framework: Java
> Installing OpenJDK 1.8...
> 
> ERROR: Unsupported Java version: 1.8
> 
> Please check your system.properties file to ensure the java.runtime.version
> is among the list of supported version on the Dev Center:
> https://devcenter.heroku.com/articles/java-support#supported-java-versions
> You can also remove the system.properties from your repo to install
> the default 1.8 version.
> If you continue to have trouble, you can open a support ticket here:
> http://help.heroku.com
> 
> Thanks,
> Heroku

Thank you for your investigation.

Romain

**Comment by ejust** [comment]
After more investigation, the problem was because we use Exoscale platform and the STACK variable is custom. So, the new code of jvm-common will not work for STACK variable different from cedar-xx : 

` DEFAULT_JDK_BASE_URL="http://lang-jvm.s3.amazonaws.com/jdk/${STACK:-"cedar-14"}`

The old version of jvm-common (v46) was fallback to a default url if not STACK variable cedar-xx is passed:

```
f [ ${STACK:-""} = "cedar" ]; then
  DEFAULT_JDK_VERSION="1.6"
  JDK_URL_1_8=${JDK_URL_1_8:-"http://lang-jvm.s3.amazonaws.com/jdk/openjdk1.8.0_20.tar.gz"}
  JDK_URL_1_7=${JDK_URL_1_7:-"http://lang-jvm.s3.amazonaws.com/jdk/openjdk1.7.0_55.tar.gz"}
  JDK_URL_1_6=${JDK_URL_1_6:-"http://lang-jvm.s3.amazonaws.com/jdk/openjdk1.6.0_27.tar.gz"}
else
  DEFAULT_JDK_VERSION="1.8"
  if [ ${STACK:-""} = "cedar-16" ]; then
    JDK_BASE_URL=${JDK_BASE_URL:-"http://lang-jvm.s3.amazonaws.com/jdk/cedar-16"}
  else
    JDK_BASE_URL=${JDK_BASE_URL:-"http://lang-jvm.s3.amazonaws.com/jdk/cedar-14"}
  fi
  JDK_URL_1_9=${JDK_URL_1_9:-"$JDK_BASE_URL/openjdk9-ea-134.tar.gz"}
  JDK_URL_1_8=${JDK_URL_1_8:-"$JDK_BASE_URL/openjdk1.8.0_102.tar.gz"}
  JDK_URL_1_7=${JDK_URL_1_7:-"$JDK_BASE_URL/openjdk1.7.0_111.tar.gz"}
  JDK_URL_1_6=${JDK_URL_1_6:-"http://lang-jvm.s3.amazonaws.com/jdk/openjdk1.6.0_27.tar.gz"}
fi

```
So, it's not really a bug, but it's not working with custom STACK variable (used by exoscale).
Our workaround was to fork the heroku java build pack and hard coding the URL of jvm-common to version 46.

**Comment by jkutner** [comment]
This buildpack requires a valid `$STACK` env var. If you are not running on Heroku, you should set the `$JDK_URL_1_8` or `$JDK_BASE_URL`. I'm closing this as "won't fix" but we can revisit if have trouble with those workarounds.
