### ISSUE TITLE
SSL certificate verification is disabled for heap dump uploads to S3

### ISSUE THREAD

**Issue by edmorley** [heroku/heroku-buildpack-jvm-common#26]
Heap dump uploads performed via [opt/with_jmap_java](https://github.com/heroku/heroku-buildpack-jvm-common/blob/master/opt/with_jmap_java) or [opt/with_jmap_and_jstack_java](https://github.com/heroku/heroku-buildpack-jvm-common/blob/master/opt/with_jmap_and_jstack_java) pass the `-k` parameter to curl, which disables SSL certificate verification.

This was deliberately added by #22, but doesn't seem wise.

Similar to my comments in #25, AWS offers wildcard certificates for buckets accessed via their subdomain, so disabling SSL certificates should not be necessary. The only time validation won't succeed is if the bucket name contains a period (see [here](https://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html)), but that case could be detected specifically (and either fail with an error message, or `-k` passed but a warning output). (There might be another option of always uploading to the non-subdomain path, but it's unclear from [the PUT docs](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html) whether that's supported.)

In addition, #22 mentioned:
> This failure is never reported, though, since cURL only reports SSL failure when verbose output is enabled (and silence [-s] is enabled anyways).

The part about requiring verbose mode (`-v`) is not correct (at least with the curl version I'm using):
```bash
$ curl -X PUT https://bucket.name.with.periods.s3.amazonaws.com/
curl: (51) SSL: no alternative certificate subject name matches target host name 'bucket.name.with.periods.s3.amazonaws.com'
```

However I would recommend adding `-S` to the curl options, so in the case of errors they are still output even though `-s` has been passed.

**Comment by jkutner** [comment]
I'm going to close this because the `with_*` scripts have been effectively phased out. We recommend `heroku java:jmap` from the CLI instead.
