### ISSUE TITLE
OpenJDK 1.7 Patchlevel 141, missing class sun/net/www/http/KeepAliveCleanerEntry

### ISSUE THREAD

**Issue by Soulou** [heroku/heroku-buildpack-jvm-common#29]
Hi there, in last openjdk 7 package https://lang-jvm.s3.amazonaws.com/jdk/cedar-14/openjdk1.7.0_141.tar.gz, the java class included in `jre/lib/rt.jar` named `sun/net/www/http/KeepAliveCleanerEntry` is not available anymore.

This package was present in the patchlevel 111: `https://lang-jvm.s3.amazonaws.com/jdk/cedar-14/openjdk1.7.0_111.tar.gz`

Could you explain this change? Was there an issue in the packaging? I've found nothing in the OpenJDK changelog about this.

Thanks a lot,

**Comment by Soulou** [comment]
What is especially weird is that the class `sun/net/www/http/KeepAliveStreamCleaner` is using the `KeepAliveCleanerEntry` in

```
extends LinkedList<KeepAliveCleanerEntry>
```

Bur definitely, impossible to find the trace of this class in the `rt.jar` file of the distributed tarball

**Comment by jkutner** [comment]
@Soulou I think that's very likely a bug in the IcedTea packing we use. I'll investigate, but in the meantime I recommend using the Zulu JDK 7 by putting the following in your `system.properties`:

```
java.runtime.version=zulu-1.7.0_154
```

For a full list of available versions see the [Java Support article on Dev Center](https://devcenter.heroku.com/articles/java-support#using-the-zulu-jdk).

**Comment by jkutner** [comment]
This has been resolved. Please let us know if you continue to have issues.
