### ISSUE TITLE
Disable sslmode when using in-dyno database

### ISSUE THREAD

**Issue by jkutner** [heroku/heroku-buildpack-jvm-common#76]
The `jdbc.sh` profile.d script adds `sslmode=require` for all JDBC URLs (including `JDBC_DATABASE_URL` and `SPRING_DATASOURCE_URL`). This is problematic when using an in-dyno database, such as the one provided by [heroku-buildpack-ci-postgresql](https://github.com/heroku/heroku-buildpack-ci-postgresql) during CI.

We should attempt to detect if the in-dyno database is being use, and if they app is running in CI and set `sslmode=disable` instead.

**Comment by seijikohara** [comment]
Is there no workaround?

**Comment by jkutner** [comment]
@seijikohara you can parse the `DATABASE_URL` manually as described in [our Dev Center docs](https://devcenter.heroku.com/articles/connecting-to-relational-databases-on-heroku-with-java#using-the-database_url-in-plain-jdbc), or you can parse the `JDBC_DATABASE_URL` and strip off the `sslmode=require` param in test environment. If necessary, you can also configure `DISABLE_SPRING_DATASOURCE_URL=true` in your `app.json`. I hope this helps for now.
