### ISSUE TITLE
Support more JVMs, like OpenJ9 or Corretto 

### ISSUE THREAD

**Issue by jtjeferreira** [heroku/heroku-buildpack-jvm-common#84]
Any plans to support other JVMs than opendJDK and zulu, for example [OpenJ9](https://www.eclipse.org/openj9/) or [Corretto](https://aws.amazon.com/corretto/)

**Comment by jkutner** [comment]
@jtjeferreira Thanks for opening this issue. Adding support for an new JDK to the official buildpack is something Heroku does very carefully, and we haven't chosen to adopt either OpenJ9 or Corretto yet (we may in the future if we get the request enough).

However, I think a third-party buildpack that installs these JDKs is a great candidate for the [Buildpack Registry](https://devcenter.heroku.com/articles/buildpack-registry). I'd be happy to add hooks to this buildpack that make it easier, and even hack on some of the new buildpack's code. One challenge might be speed--the download may be slower than the official Heroku JDKs and there would probably be a bit of time required to strip docs/samples/debug symbols out of the JDKs to prevent slugs from growing by 100MB. 

Please let me know what you think. Thanks again.

**Comment by jtjeferreira** [comment]
Since the support for zulu exists here I thought this would be a good place for other JVMs support...

However a third-party buildpack would be a good place to start...

**Comment by jkutner** [comment]
@jtjeferreira I made this just for you: http://jkutner.github.io/2019/03/27/using-corretto-adopt-graal-zulu-on-heroku.html :)

I'm going to close this because we don't intend to add support for any more JDKs directly to this buildpack. If any particular JDK gains significant traction we'll revisit. Thanks for opening the issue!

**Comment by xqliu** [comment]
This is also another build pack using IBM OpenJ9, I found this one actually has much smaller memory usage


[#muyantech/openj9-buildpack](https://elements.heroku.com/buildpacks/muyantech/openj9-buildpack)
