### ISSUE TITLE
Is there another way to install jvm/java on heroku?

### ISSUE THREAD

**Issue by Jackclarify** [heroku/heroku-buildpack-jvm-common#96]
Hi @jkutner, I have a question same with [this issue](https://stackoverflow.com/questions/51447603/nodejs-app-with-java-on-heroku#), and after installing the jvm by following your suggestion, it works well.

But I checked my other heroku instances(using cedar-14-stack), which have java installed without jvm buildpack.
**instance name   / stack              / has java installed**
test-staging            / heroku-18     / no
rock                        / heroku-16     / no
test2-staging          / cedar-14       / yes

Refer to heroku-16-stack#what-s-new:
The JDK is installed by the Java/JVM buildpack. If you have an app that uses Java, but not the Java buildpack (e.g., jython or a Java Bridge), you’ll have to set the JVM buildpack on your app (instructions are listed below). [Here is docs](https://devcenter.heroku.com/articles/heroku-16-stack#what-s-new)
Does it mean that heroku-16 stack or higher need to set jvm buildpack if using java?

Is there other ways or another configuration to have java installed defaultly on heroku nodejs instances? Such as add script(apt install default-jre) circleci config.yml?

**Comment by jkutner** [comment]
Using the `heroku buildpacks:add heroku/jvm` is how we recommend adding the JDK to your app.

**Comment by Jackclarify** [comment]
@jkutner Okay, thank you for your help. Thanks :)
